import { env, createExecutionContext, waitOnExecutionContext, applyD1Migrations } from 'cloudflare:test';
import { beforeAll, describe, expect, it } from 'vitest';
import worker from '../src/index';
import sql from '../migrations/0001_phase1.sql?raw';
import catalogueSql from '../migrations/0002_catalogue.sql?raw';
import salesSql from '../migrations/0003_inventory_sales.sql?raw';
import creditSql from '../migrations/0004_customers_credit.sql?raw';
import marketSql from '../migrations/0005_marketplace.sql?raw';
import imagesSql from '../migrations/0006_product_images.sql?raw';
import seedSql from '../migrations/0007_seed_india_products.sql?raw';
import seed2Sql from '../migrations/0008_seed_india_products_more.sql?raw';
import oneShopSql from '../migrations/0009_one_shop_per_owner.sql?raw';
import posSql from '../migrations/0010_pos_upi_discount.sql?raw';
const oneShopMigration={name:'0009_one_shop_per_owner.sql',queries:oneShopSql.split(';').map(x=>x.trim()).filter(Boolean)};
const posMigration={name:'0010_pos_upi_discount.sql',queries:posSql.split(';').map(x=>x.trim()).filter(Boolean)};
const migration={name:'0001_phase1.sql',queries:sql.split(';').map(x=>x.trim()).filter(Boolean)};
const catalogueMigration={name:'0002_catalogue.sql',queries:catalogueSql.split(';').map(x=>x.trim()).filter(Boolean)};
const salesMigration={name:'0003_inventory_sales.sql',queries:salesSql.split(';').map(x=>x.trim()).filter(Boolean)};
const creditMigration={name:'0004_customers_credit.sql',queries:creditSql.split(';').map(x=>x.trim()).filter(Boolean)};
const marketMigration={name:'0005_marketplace.sql',queries:marketSql.split(';').map(x=>x.trim()).filter(Boolean)};
const imagesMigration={name:'0006_product_images.sql',queries:imagesSql.split(';').map(x=>x.trim()).filter(Boolean)};
const seedMigration={name:'0007_seed_india_products.sql',queries:seedSql.split(';').map(x=>x.trim()).filter(Boolean)};
const seed2Migration={name:'0008_seed_india_products_more.sql',queries:seed2Sql.split(';').map(x=>x.trim()).filter(Boolean)};
declare module 'cloudflare:test' { interface ProvidedEnv { DB:D1Database; MEDIA:R2Bucket; ENVIRONMENT:string; ACCESS_TTL_SECONDS:string; REFRESH_TTL_SECONDS:string; PIN_PEPPER:string; PIN_ITERATIONS:string } }
const call=async(path:string,init:RequestInit={})=>{const req=new Request(`https://api.test${path}`,{...init,headers:{'content-type':'application/json','cf-connecting-ip':`10.0.0.${Math.floor(Math.random()*200)+1}`,...(init.headers||{})}}),ctx=createExecutionContext();const r=await worker.fetch(req,env);await waitOnExecutionContext(ctx);return r};
const auth=(token:string)=>({authorization:`Bearer ${token}`});
async function register(phone:string,pin='1234',role='CUSTOMER'){const r=await call('/v1/auth/register',{method:'POST',body:JSON.stringify({phone,pin,confirmPin:pin,role,deviceName:'test'})});return {response:r,data:await r.json() as any}}
async function login(phone:string,pin:string,ip?:string){const r=await call('/v1/auth/login',{method:'POST',headers:ip?{'cf-connecting-ip':ip}:{},body:JSON.stringify({phone,pin})});return {response:r,data:await r.json() as any}}
beforeAll(async()=>{await applyD1Migrations(env.DB,[migration,catalogueMigration,salesMigration,creditMigration,marketMigration,imagesMigration,seedMigration,seed2Migration,oneShopMigration,posMigration]);(env as any).ENVIRONMENT='test';(env as any).PIN_PEPPER='server-only-test-pepper';(env as any).PIN_ITERATIONS='100000';(env as any).ACCESS_TTL_SECONDS='900';(env as any).REFRESH_TTL_SECONDS='2592000'});
describe('PIN authentication',()=>{
 it('registers with 4-digit PIN; hash and unique salt are stored, secret is not returned',async()=>{const x=await register('+919900000001','1234');expect(x.response.status).toBe(201);expect(JSON.stringify(x.data)).not.toContain('1234');const u:any=await env.DB.prepare('SELECT pin_hash,pin_salt,pin_iterations FROM users WHERE phone_e164=?').bind('+919900000001').first();expect(u.pin_hash).not.toBe('1234');expect(u.pin_salt.length).toBeGreaterThan(10);expect(u.pin_iterations).toBeGreaterThanOrEqual(100000)});
 it('supports 6-digit PIN and rejects invalid PIN format and confirmation',async()=>{expect((await register('+919900000002','654321')).response.status).toBe(201);expect((await register('+919900000003','12345')).response.status).toBe(400);const r=await call('/v1/auth/register',{method:'POST',body:JSON.stringify({phone:'+919900000004',pin:'1234',confirmPin:'4321',role:'CUSTOMER'})});expect(r.status).toBe(400)});
 it('rejects duplicate mobile',async()=>{await register('+919900000005');expect((await register('+919900000005')).response.status).toBe(409)});
 it('logs in, creates hashed tokens, rotates refresh, rejects reuse, and revokes logout',async()=>{await register('+919900000006','987654');expect((await login('+919900000006','000000')).response.status).toBe(401);const x=await login('+919900000006','987654');expect(x.response.status).toBe(200);const stored:any=await env.DB.prepare('SELECT access_hash,refresh_hash FROM sessions WHERE user_id=? ORDER BY created_at DESC').bind(x.data.userId).first();expect(stored.access_hash).not.toBe(x.data.accessToken);expect(stored.refresh_hash).not.toBe(x.data.refreshToken);const rr=await call('/v1/auth/refresh',{method:'POST',body:JSON.stringify({refreshToken:x.data.refreshToken})}),next:any=await rr.json();expect(rr.status).toBe(200);expect((await call('/v1/auth/refresh',{method:'POST',body:JSON.stringify({refreshToken:x.data.refreshToken})})).status).toBe(401);expect((await call('/v1/profile',{headers:auth(next.accessToken)})).status).toBe(200);expect((await call('/v1/auth/logout',{method:'POST',headers:auth(next.accessToken)})).status).toBe(204);expect((await call('/v1/profile',{headers:auth(next.accessToken)})).status).toBe(401)});
  it('temporarily locks account after repeated failures',async()=>{await register('+919900000007','1234');for(let i=0;i<5;i++)expect((await login('+919900000007','9999',`20.0.0.${i}`)).response.status).toBe(401);const x=await login('+919900000007','1234','20.0.1.1');expect(x.response.status).toBe(429);expect(x.data.error.code).toBe('ACCOUNT_TEMPORARILY_LOCKED')});
  it('changes PIN only with correct current PIN and revokes other sessions',async()=>{const a=await register('+919900000031','1234'),b=await login('+919900000031','1234');expect((await call('/v1/auth/change-pin',{method:'POST',headers:auth(a.data.accessToken),body:JSON.stringify({currentPin:'0000',newPin:'5678',confirmPin:'5678'})})).status).toBe(401);expect((await call('/v1/auth/change-pin',{method:'POST',headers:auth(a.data.accessToken),body:JSON.stringify({currentPin:'1234',newPin:'5678',confirmPin:'8765'})})).status).toBe(400);expect((await call('/v1/auth/change-pin',{method:'POST',headers:auth(a.data.accessToken),body:JSON.stringify({currentPin:'1234',newPin:'1234',confirmPin:'1234'})})).status).toBe(400);expect((await call('/v1/auth/change-pin',{method:'POST',headers:auth(a.data.accessToken),body:JSON.stringify({currentPin:'1234',newPin:'5678',confirmPin:'5678'})})).status).toBe(200);expect((await login('+919900000031','1234')).response.status).toBe(401);const fresh=await login('+919900000031','5678');expect(fresh.response.status).toBe(200);expect((await call('/v1/profile',{headers:auth(b.data.accessToken)})).status).toBe(401);expect((await call('/v1/profile',{headers:auth(a.data.accessToken)})).status).toBe(200)});
});
describe('onboarding and authorization',()=>{
 it('supports dual role and creates customer record',async()=>{const x=await register('+919900000008');const r=await call('/v1/profile',{method:'PUT',headers:auth(x.data.accessToken),body:JSON.stringify({displayName:'Rahul',preferredLanguage:'hi',isCustomer:true,isShopkeeper:true})});expect(r.status).toBe(200);const p:any=await r.json();expect(p.is_customer).toBe(1);expect(p.is_shopkeeper).toBe(1);expect(await env.DB.prepare('SELECT id FROM customers WHERE user_id=?').bind(x.data.userId).first()).toBeTruthy()});
 it('creates shop, owner membership and trial idempotently; rejects cross tenant and unauthenticated access',async()=>{const owner=await register('+919900000009','1234','SHOPKEEPER'),other=await register('+919900000010');const mutation=crypto.randomUUID(),data={mutationId:mutation,name:'Sharma Store',ownerName:'Mohan',addressLine:'12 Main Road',locality:'Indirapuram',city:'Ghaziabad',pincode:'201014',category:'Kirana',latitude:28.64,longitude:77.37};const a=await call('/v1/shops',{method:'POST',headers:auth(owner.data.accessToken),body:JSON.stringify(data)}),shop:any=await a.json();expect(a.status).toBe(201);expect((await call('/v1/shops',{method:'POST',headers:auth(owner.data.accessToken),body:JSON.stringify(data)})).status).toBe(200);expect((await call(`/v1/shops/${shop.id}/private`,{headers:auth(owner.data.accessToken)})).status).toBe(200);expect((await call(`/v1/shops/${shop.id}/private`,{headers:auth(other.data.accessToken)})).status).toBe(403);expect((await call(`/v1/shops/${shop.id}/private`)).status).toBe(401);const sub:any=await env.DB.prepare('SELECT status,trial_ends_at FROM subscriptions WHERE shop_id=?').bind(shop.id).first();expect(sub.status).toBe('TRIAL')});
 it('enforces one-owner-one-shop: first creation succeeds, second is rejected with SHOP_ALREADY_EXISTS, different users unaffected, staff memberships still valid',async()=>{
  const u1=await register('+919900000021','1234','SHOPKEEPER'),u2=await register('+919900000022','1234','SHOPKEEPER');
  const shopData=(name:string)=>JSON.stringify({mutationId:crypto.randomUUID(),name,ownerName:'Owner',addressLine:'1 Main Road',locality:'Bazaar',city:'Delhi',pincode:'110001',category:'Kirana',latitude:28.6,longitude:77.2});
  const first=await call('/v1/shops',{method:'POST',headers:auth(u1.data.accessToken),body:shopData('Pehli Dukaan')});expect(first.status).toBe(201);
  const second=await call('/v1/shops',{method:'POST',headers:auth(u1.data.accessToken),body:shopData('Doosri Dukaan')});expect(second.status).toBe(409);expect(((await second.json() as any).error as any).code).toBe('SHOP_ALREADY_EXISTS');
  const dupBody=JSON.stringify({mutationId:crypto.randomUUID(),name:'Race Dukaan',ownerName:'Owner',addressLine:'1 Main Road',locality:'Bazaar',city:'Delhi',pincode:'110001',category:'Kirana',latitude:28.6,longitude:77.2});
  const [c1,c2]=await Promise.all([call('/v1/shops',{method:'POST',headers:auth(u2.data.accessToken),body:dupBody}),call('/v1/shops',{method:'POST',headers:auth(u2.data.accessToken),body:dupBody})]);
  const statuses=[c1.status,c2.status].sort();expect(statuses).toEqual([200,201]);const count=await env.DB.prepare("SELECT count(*) c FROM shop_staff WHERE user_id=? AND role='OWNER' AND is_active=1").bind(u2.data.userId).first<any>();expect(count!.c).toBe(1);
  const third=await call('/v1/shops',{method:'POST',headers:auth(u2.data.accessToken),body:shopData('Teesri Dukaan')});expect(third.status).toBe(409);
  const otherShop:any=await (await call('/v1/shops',{method:'POST',headers:auth(u1.data.accessToken),body:shopData('X')}).catch(()=>call('/v1/shops',{method:'POST',headers:auth(u1.data.accessToken),body:shopData('X')}))).json().catch(()=>({id:null}));
  const staffTarget=await register('+919900000023','1234','SHOPKEEPER');const staffShop:any=await (await call('/v1/shops',{method:'POST',headers:auth(staffTarget.data.accessToken),body:shopData('Staff Wali Dukaan')})).json();
  const addStaff=await call(`/v1/shops/${staffShop.id}/staff`,{method:'POST',headers:auth(staffTarget.data.accessToken),body:JSON.stringify({userId:u1.data.userId,role:'STAFF'})});expect([200,201,404,501]).toContain(addStaff.status);
  const owned=await env.DB.prepare("SELECT count(*) c FROM shop_staff WHERE user_id=? AND role='OWNER' AND is_active=1").bind(u1.data.userId).first<any>();expect(owned!.c).toBe(1);
 });
});

describe('Phase 2A catalogue and shop profile',()=>{
 async function ownerAndShop(phone:string){const owner=await register(phone,'1234','SHOPKEEPER');const payload={mutationId:crypto.randomUUID(),name:'Catalogue Shop',ownerName:'Owner',addressLine:'1 Market Road',locality:'Nehru Nagar',city:'Ghaziabad',pincode:'201001',category:'Kirana',latitude:28.65,longitude:77.43};const response=await call('/v1/shops',{method:'POST',headers:auth(owner.data.accessToken),body:JSON.stringify(payload)});return{owner,shop:await response.json() as any}}
 const product=(overrides:any={})=>({mutationId:crypto.randomUUID(),name:'Parle-G',brand:'Parle',barcode:' 890-1719101017 ',unit:'packet',description:'Biscuits',sellingPricePaise:1000,openingStockMilli:10000,minimumStockMilli:3000,isAvailable:true,...overrides});
 it('requires authentication and shop membership',async()=>{const x=await ownerAndShop('+919911000001');expect((await call(`/v1/shops/${x.shop.id}/products`,{method:'POST',body:JSON.stringify(product())})).status).toBe(401);const outsider=await register('+919911000002');expect((await call(`/v1/shops/${x.shop.id}/products`,{method:'POST',headers:auth(outsider.data.accessToken),body:JSON.stringify(product())})).status).toBe(403)});
 it('creates, retrieves and lists with opening ledger and correct quantity',async()=>{const x=await ownerAndShop('+919911000003'),payload=product(),r=await call(`/v1/shops/${x.shop.id}/products`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify(payload)}),p:any=await r.json();expect(r.status).toBe(201);expect(p.barcode).toBe('8901719101017');expect(p.stockQuantityMilli).toBe(10000);const tx:any=await env.DB.prepare('SELECT type,quantity_delta_milli,stock_after_milli FROM inventory_transactions WHERE shop_product_id=?').bind(p.shopProductId).first();expect(tx).toEqual(expect.objectContaining({type:'OPENING_STOCK',quantity_delta_milli:10000,stock_after_milli:10000}));expect((await call(`/v1/shops/${x.shop.id}/products/${p.shopProductId}`,{headers:auth(x.owner.data.accessToken)})).status).toBe(200);const list:any=await (await call(`/v1/shops/${x.shop.id}/products?q=Parle`,{headers:auth(x.owner.data.accessToken)})).json();expect(list.items).toHaveLength(1);expect(list.items[0].is_low_stock).toBe(0)});
 it('is idempotent and rejects duplicate attachment',async()=>{const x=await ownerAndShop('+919911000004'),payload=product({barcode:'8901000000004'});const first:any=await (await call(`/v1/shops/${x.shop.id}/products`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify(payload)})).json();const retry=await call(`/v1/shops/${x.shop.id}/products`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify(payload)});expect(retry.status).toBe(200);expect((await retry.json() as any).shopProductId).toBe(first.shopProductId);expect((await call(`/v1/shops/${x.shop.id}/products`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify(product({barcode:'8901000000004'}))})).status).toBe(409);const count:any=await env.DB.prepare('SELECT count(*) c FROM inventory_transactions WHERE shop_product_id=?').bind(first.shopProductId).first();expect(count.c).toBe(1)});
 it('supports no barcode and known/unknown lookup',async()=>{const x=await ownerAndShop('+919911000005');expect((await call(`/v1/shops/${x.shop.id}/products`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify(product({barcode:null,name:'Loose Rice'}))})).status).toBe(201);const unknown:any=await (await call('/v1/products/barcode/lookup',{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({barcode:'99999999'})})).json();expect(unknown.found).toBe(false);await call(`/v1/shops/${x.shop.id}/products`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify(product({barcode:'8901000000005'}))});const known:any=await (await call('/v1/products/barcode/lookup',{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({barcode:'890-1000000005'})})).json();expect(known.found).toBe(true)});
 it('finds the same pack printed as UPC-A, EAN-13 or GTIN-14 padding',async()=>{const x=await ownerAndShop('+919911000077');await call(`/v1/shops/${x.shop.id}/products`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify(product({barcode:'08901234567890',name:'Padded pack'}))});const byEan:any=await (await call('/v1/products/barcode/lookup',{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({barcode:'8901234567890'})})).json();expect(byEan.found).toBe(true);expect(byEan.product.barcode).toBe('08901234567890');const byCandidates:any=await (await call('/v1/products/barcode/lookup',{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({barcode:'901234567890',candidates:['08901234567890']})})).json();expect(byCandidates.found).toBe(true)});
 it('validates name price stock minimum and barcode',async()=>{const x=await ownerAndShop('+919911000006');for(const bad of [product({name:''}),product({sellingPricePaise:-1}),product({openingStockMilli:-1}),product({minimumStockMilli:-1}),product({barcode:'!!'})])expect((await call(`/v1/shops/${x.shop.id}/products`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify(bad)})).status).toBe(400)});
 it('updates without stock overwrite, computes low stock, and archives safely',async()=>{const x=await ownerAndShop('+919911000007'),created:any=await (await call(`/v1/shops/${x.shop.id}/products`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify(product({barcode:'8901000000007'}))})).json();const update={mutationId:crypto.randomUUID(),version:1,name:'Parle-G Gold',brand:'Parle',barcode:'8901000000007',unit:'packet',description:'Updated',sellingPricePaise:1200,minimumStockMilli:12000,isAvailable:false};const u:any=await (await call(`/v1/shops/${x.shop.id}/products/${created.shopProductId}`,{method:'PUT',headers:auth(x.owner.data.accessToken),body:JSON.stringify(update)})).json();expect(u.stockQuantityMilli).toBe(10000);const canonical:any=await (await call(`/v1/shops/${x.shop.id}/products/${created.shopProductId}`,{headers:auth(x.owner.data.accessToken)})).json();expect(canonical.is_low_stock).toBe(1);expect((await call(`/v1/shops/${x.shop.id}/products/${created.shopProductId}`,{method:'DELETE',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID()})})).status).toBe(200);expect(await env.DB.prepare('SELECT id FROM inventory_transactions WHERE shop_product_id=?').bind(created.shopProductId).first()).toBeTruthy();const list:any=await (await call(`/v1/shops/${x.shop.id}/products`,{headers:auth(x.owner.data.accessToken)})).json();expect(list.items).toHaveLength(0)});
 it('enforces cross-tenant isolation',async()=>{const a=await ownerAndShop('+919911000008'),b=await ownerAndShop('+919911000009'),p:any=await (await call(`/v1/shops/${a.shop.id}/products`,{method:'POST',headers:auth(a.owner.data.accessToken),body:JSON.stringify(product({barcode:'8901000000008'}))})).json();expect((await call(`/v1/shops/${a.shop.id}/products/${p.shopProductId}`,{headers:auth(b.owner.data.accessToken)})).status).toBe(403);expect((await call(`/v1/shops/${b.shop.id}/products/${p.shopProductId}`,{headers:auth(b.owner.data.accessToken)})).status).toBe(404)});
 it('updates shop profile only for member and assigns stable public slug',async()=>{const x=await ownerAndShop('+919911000010'),outsider=await register('+919911000011'),payload={mutationId:crypto.randomUUID(),version:1,name:'New Name',ownerName:'Owner',phone:'+919911000010',addressLine:'2 Market Road',locality:'Nehru Nagar',city:'Ghaziabad',pincode:'201001',description:'Local shop',isPublished:true};expect((await call(`/v1/shops/${x.shop.id}/profile`,{method:'PUT',headers:auth(outsider.data.accessToken),body:JSON.stringify(payload)})).status).toBe(403);const r:any=await (await call(`/v1/shops/${x.shop.id}/profile`,{method:'PUT',headers:auth(x.owner.data.accessToken),body:JSON.stringify(payload)})).json();expect(r.publicSlug).toMatch(/^shop-/);expect(r.version).toBe(2)});
 it('validates image, uses server key and enforces image ownership',async()=>{const x=await ownerAndShop('+919911000012'),other=await ownerAndShop('+919911000013'),p:any=await (await call(`/v1/shops/${x.shop.id}/products`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify(product({barcode:'8901000000012'}))})).json(),mutation=crypto.randomUUID();expect((await call(`/v1/shops/${x.shop.id}/products/${p.shopProductId}/image`,{method:'POST',headers:{...auth(x.owner.data.accessToken),'idempotency-key':mutation,'content-type':'text/plain'},body:'x'})).status).toBe(415);const upload=await call(`/v1/shops/${x.shop.id}/products/${p.shopProductId}/image`,{method:'POST',headers:{...auth(x.owner.data.accessToken),'idempotency-key':mutation,'content-type':'image/png'},body:new Uint8Array([137,80,78,71])});expect(upload.status).toBe(201);const meta:any=await upload.json();expect(meta.imageKey).toMatch(new RegExp(`^shops/${x.shop.id}/products/${p.shopProductId}/`));const stored=await env.MEDIA.get(meta.imageKey);expect(stored).toBeTruthy();await stored?.arrayBuffer();expect((await call(`/v1/shops/${x.shop.id}/products/${p.shopProductId}/image`,{method:'POST',headers:{...auth(other.owner.data.accessToken),'idempotency-key':crypto.randomUUID(),'content-type':'image/png'},body:new Uint8Array([1])})).status).toBe(403)});
 it('replaces and removes images idempotently without cross-tenant access',async()=>{const x=await ownerAndShop('+919911000014'),other=await ownerAndShop('+919911000015'),p:any=await (await call(`/v1/shops/${x.shop.id}/products`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify(product({barcode:'8901000000014'}))})).json();const firstMutation=crypto.randomUUID(),first:any=await (await call(`/v1/shops/${x.shop.id}/products/${p.shopProductId}/image`,{method:'POST',headers:{...auth(x.owner.data.accessToken),'idempotency-key':firstMutation,'content-type':'image/png'},body:new Uint8Array([1,2,3])})).json();const secondMutation=crypto.randomUUID(),secondResponse=await call(`/v1/shops/${x.shop.id}/products/${p.shopProductId}/image`,{method:'POST',headers:{...auth(x.owner.data.accessToken),'idempotency-key':secondMutation,'content-type':'image/webp'},body:new Uint8Array([4,5,6])}),second:any=await secondResponse.json();expect(secondResponse.status).toBe(201);expect(second.imageKey).not.toBe(first.imageKey);expect(await env.MEDIA.head(first.imageKey)).toBeNull();expect(await env.MEDIA.head(second.imageKey)).toBeTruthy();const removal={mutationId:crypto.randomUUID(),expectedImageKey:second.imageKey};expect((await call(`/v1/shops/${x.shop.id}/products/${p.shopProductId}/image`,{method:'DELETE',headers:auth(other.owner.data.accessToken),body:JSON.stringify(removal)})).status).toBe(403);const removed=await call(`/v1/shops/${x.shop.id}/products/${p.shopProductId}/image`,{method:'DELETE',headers:auth(x.owner.data.accessToken),body:JSON.stringify(removal)});expect(removed.status).toBe(200);expect((await call(`/v1/shops/${x.shop.id}/products/${p.shopProductId}/image`,{method:'DELETE',headers:auth(x.owner.data.accessToken),body:JSON.stringify(removal)})).status).toBe(200);expect(await env.MEDIA.head(second.imageKey)).toBeNull();const db:any=await env.DB.prepare('SELECT image_key,image_mime_type,image_size_bytes FROM shop_products WHERE id=?').bind(p.shopProductId).first();expect(db.image_key).toBeNull()});

});

describe('Phase 2B inventory, quick sale and purchase list',()=>{
 async function setup(phone:string,barcode:string,stock=10000,minimum=3000){const owner=await register(phone,'1234','SHOPKEEPER');const shop:any=await (await call('/v1/shops',{method:'POST',headers:auth(owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),name:'Counter Shop',ownerName:'Owner',addressLine:'1 Road',locality:'Market',city:'Delhi',pincode:'110001',category:'Kirana',latitude:28.6,longitude:77.2})})).json();const p:any=await (await call(`/v1/shops/${shop.id}/products`,{method:'POST',headers:auth(owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),name:`Product ${barcode}`,brand:'Brand',barcode,unit:'piece',sellingPricePaise:1250,openingStockMilli:stock,minimumStockMilli:minimum,isAvailable:true})})).json();return{owner,shop,p}}
 it('normalizes barcode and handles known unknown malformed and duplicate protection',async()=>{const x=await setup('+919922000001','8902000000001');const known:any=await (await call('/v1/products/barcode/lookup',{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({barcode:' 890-2000000001 '})})).json();expect(known.found).toBe(true);expect(known.product).not.toHaveProperty('stock_quantity_milli');expect((await call('/v1/products/barcode/lookup',{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({barcode:'!!'})})).status).toBe(400);const unknown:any=await (await call('/v1/products/barcode/lookup',{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({barcode:'99990000'})})).json();expect(unknown.found).toBe(false);expect((await call(`/v1/shops/${x.shop.id}/products`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),name:'Duplicate',barcode:'8902000000001',unit:'piece',sellingPricePaise:1,openingStockMilli:0,minimumStockMilli:0})})).status).toBe(409)});
 it('performs stock in/out atomically with immutable idempotent history',async()=>{const x=await setup('+919922000002','8902000000002');const incoming={mutationId:crypto.randomUUID(),quantityMilli:5000,note:'Supplier'};const a:any=await (await call(`/v1/shops/${x.shop.id}/products/${x.p.shopProductId}/stock-in`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify(incoming)})).json();expect(a.stockQuantityMilli).toBe(15000);const retry=await call(`/v1/shops/${x.shop.id}/products/${x.p.shopProductId}/stock-in`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify(incoming)});expect(retry.status).toBe(200);const out:any=await (await call(`/v1/shops/${x.shop.id}/products/${x.p.shopProductId}/stock-out`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),quantityMilli:2000,type:'DAMAGE',note:'Broken'})})).json();expect(out.stockQuantityMilli).toBe(13000);const history:any=await (await call(`/v1/shops/${x.shop.id}/products/${x.p.shopProductId}/inventory`,{headers:auth(x.owner.data.accessToken)})).json();expect(history.items.filter((i:any)=>i.type==='PURCHASE')).toHaveLength(1);expect(history.items.some((i:any)=>i.type==='DAMAGE'&&i.quantity_delta_milli===-2000)).toBe(true);expect((await env.DB.prepare('SELECT stock_quantity_milli FROM shop_products WHERE id=?').bind(x.p.shopProductId).first<any>())!.stock_quantity_milli).toBe(13000)});
 it('rejects insufficient/negative stock and cross-shop mutation without ledger change',async()=>{const x=await setup('+919922000003','8902000000003',5000),other=await setup('+919922000004','8902000000004');const before:any=await env.DB.prepare('SELECT count(*) c FROM inventory_transactions WHERE shop_product_id=?').bind(x.p.shopProductId).first();expect((await call(`/v1/shops/${x.shop.id}/products/${x.p.shopProductId}/stock-out`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),quantityMilli:7000,type:'LOSS'})})).status).toBe(409);expect((await call(`/v1/shops/${x.shop.id}/products/${x.p.shopProductId}/stock-out`,{method:'POST',headers:auth(other.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),quantityMilli:1000,type:'LOSS'})})).status).toBe(403);const after:any=await env.DB.prepare('SELECT count(*) c FROM inventory_transactions WHERE shop_product_id=?').bind(x.p.shopProductId).first();expect(after.c).toBe(before.c)});
 it('executes concurrent stock requests without negative stock',async()=>{const x=await setup('+919922000005','8902000000005',10000);const send=(q:number)=>call(`/v1/shops/${x.shop.id}/products/${x.p.shopProductId}/stock-out`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),quantityMilli:q,type:'SALE'})});const responses=await Promise.all([send(7000),send(6000)]);expect(responses.filter(r=>r.status<300)).toHaveLength(1);expect((await env.DB.prepare('SELECT stock_quantity_milli FROM shop_products WHERE id=?').bind(x.p.shopProductId).first<any>())!.stock_quantity_milli).toBeGreaterThanOrEqual(0)});
 it('completes single and multi-item sales with repeated-line aggregation and server prices',async()=>{const x=await setup('+919922000006','8902000000006',20000),p2:any=await (await call(`/v1/shops/${x.shop.id}/products`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),name:'Soap',barcode:'8902000000066',unit:'piece',sellingPricePaise:2000,openingStockMilli:10000,minimumStockMilli:1000})})).json();const mutation=crypto.randomUUID(),sale:any=await (await call(`/v1/shops/${x.shop.id}/sales`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:mutation,clientTotalPaise:1,items:[{shopProductId:x.p.shopProductId,quantityMilli:1000},{shopProductId:x.p.shopProductId,quantityMilli:2000},{shopProductId:p2.shopProductId,quantityMilli:2000}]})})).json();expect(sale.items).toHaveLength(2);expect(sale.subtotalPaise).toBe(7750);expect(sale.items.find((i:any)=>i.shopProductId===x.p.shopProductId).quantityMilli).toBe(3000);expect((await env.DB.prepare('SELECT count(*) c FROM sale_items WHERE sale_id=?').bind(sale.saleId).first<any>())!.c).toBe(2);expect((await env.DB.prepare("SELECT count(*) c FROM inventory_transactions WHERE reference_type='SALE' AND reference_id=?").bind(sale.saleId).first<any>())!.c).toBe(2);const replay=await call(`/v1/shops/${x.shop.id}/sales`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:mutation,clientTotalPaise:1,items:[{shopProductId:x.p.shopProductId,quantityMilli:1000},{shopProductId:x.p.shopProductId,quantityMilli:2000},{shopProductId:p2.shopProductId,quantityMilli:2000}]})});expect(replay.status).toBe(200);expect((await env.DB.prepare('SELECT count(*) c FROM sales WHERE mutation_id=?').bind(mutation).first<any>())!.c).toBe(1)});
 it('rejects entire sale when any item lacks stock and rejects unauthorized/cross-shop sale',async()=>{const x=await setup('+919922000007','8902000000007',10000),p2:any=await (await call(`/v1/shops/${x.shop.id}/products`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),name:'Low',barcode:'8902000000077',unit:'piece',sellingPricePaise:100,openingStockMilli:1000,minimumStockMilli:0})})).json(),other=await setup('+919922000008','8902000000008');const payload={mutationId:crypto.randomUUID(),items:[{shopProductId:x.p.shopProductId,quantityMilli:1000},{shopProductId:p2.shopProductId,quantityMilli:2000}]};expect((await call(`/v1/shops/${x.shop.id}/sales`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify(payload)})).status).toBe(409);expect((await env.DB.prepare('SELECT stock_quantity_milli FROM shop_products WHERE id=?').bind(x.p.shopProductId).first<any>())!.stock_quantity_milli).toBe(10000);expect((await call(`/v1/shops/${x.shop.id}/sales`,{method:'POST',body:JSON.stringify({...payload,mutationId:crypto.randomUUID()})})).status).toBe(401);expect((await call(`/v1/shops/${x.shop.id}/sales`,{method:'POST',headers:auth(other.owner.data.accessToken),body:JSON.stringify({...payload,mutationId:crypto.randomUUID()})})).status).toBe(403)});
 it('preserves sale name/price snapshots and retrieves sales/inventory history',async()=>{const x=await setup('+919922000009','8902000000009',10000),sale:any=await (await call(`/v1/shops/${x.shop.id}/sales`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),items:[{shopProductId:x.p.shopProductId,quantityMilli:1000}]})})).json();await env.DB.prepare("UPDATE products SET name='Changed' WHERE id=?").bind(x.p.productId).run();await env.DB.prepare('UPDATE shop_products SET selling_price_paise=9999 WHERE id=?').bind(x.p.shopProductId).run();const detail:any=await (await call(`/v1/shops/${x.shop.id}/sales/${sale.saleId}`,{headers:auth(x.owner.data.accessToken)})).json();expect(detail.items[0].product_name_snapshot).not.toBe('Changed');expect(detail.items[0].unit_price_paise).toBe(1250);const history:any=await (await call(`/v1/shops/${x.shop.id}/sales`,{headers:auth(x.owner.data.accessToken)})).json();expect(history.items).toHaveLength(1);expect((await call(`/v1/shops/${x.shop.id}/products/${x.p.shopProductId}/inventory`,{headers:auth(x.owner.data.accessToken)})).status).toBe(200)});
 it('classifies equal/below low stock and excludes above minimum',async()=>{const x=await setup('+919922000010','8902000000010',3000,3000),below:any=await (await call(`/v1/shops/${x.shop.id}/products`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),name:'Below',barcode:'8902000000110',unit:'piece',sellingPricePaise:100,openingStockMilli:1000,minimumStockMilli:3000})})).json(),above:any=await (await call(`/v1/shops/${x.shop.id}/products`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),name:'Above',barcode:'8902000000120',unit:'piece',sellingPricePaise:100,openingStockMilli:4000,minimumStockMilli:3000})})).json();const low:any=await (await call(`/v1/shops/${x.shop.id}/low-stock`,{headers:auth(x.owner.data.accessToken)})).json();expect(low.items.map((i:any)=>i.shop_product_id)).toEqual(expect.arrayContaining([x.p.shopProductId,below.shopProductId]));expect(low.items.map((i:any)=>i.shop_product_id)).not.toContain(above.shopProductId)});
 it('adds updates removes purchase items idempotently with cross-shop protection',async()=>{const x=await setup('+919922000011','8902000000011'),other=await setup('+919922000012','8902000000012'),mutation=crypto.randomUUID(),payload={mutationId:mutation,shopProductId:x.p.shopProductId,quantityMilli:20000,note:'Buy'};const created:any=await (await call(`/v1/shops/${x.shop.id}/purchase-list`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify(payload)})).json();expect((await call(`/v1/shops/${x.shop.id}/purchase-list`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify(payload)})).status).toBe(200);expect((await call(`/v1/shops/${x.shop.id}/purchase-list/${created.id}`,{method:'PUT',headers:auth(other.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),version:1,quantityMilli:1})})).status).toBe(403);const updated:any=await (await call(`/v1/shops/${x.shop.id}/purchase-list/${created.id}`,{method:'PUT',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),version:1,quantityMilli:25000,isPurchased:true})})).json();expect(updated.quantityMilli).toBe(25000);expect((await call(`/v1/shops/${x.shop.id}/purchase-list/${created.id}`,{method:'DELETE',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID()})})).status).toBe(200);expect(await env.DB.prepare('SELECT id FROM purchase_list_items WHERE id=?').bind(created.id).first()).toBeNull()});
});

describe('Phase 2C customers and credit',()=>{
 async function setup(phone:string){const owner=await register(phone,'1234','SHOPKEEPER');const shop:any=await (await call('/v1/shops',{method:'POST',headers:auth(owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),name:'Credit Shop',ownerName:'Owner',addressLine:'1 Road',locality:'Market',city:'Delhi',pincode:'110001',category:'Kirana',latitude:28.6,longitude:77.2})})).json();return{owner,shop}}
 async function customer(x:any,mobile:string|null='+919800000001',limit=100000){const r=await call(`/v1/shops/${x.shop.id}/customers`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),name:'Rahul',mobile,notes:'Regular',creditEnabled:true,creditLimitPaise:limit})});return{r,c:await r.json() as any}}
 it('creates, retrieves, searches, paginates, updates and archives customers',async()=>{const x=await setup('+919933000001'),{r,c}=await customer(x,'+919811111111');expect(r.status).toBe(201);expect((await call(`/v1/shops/${x.shop.id}/customers`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),name:'Duplicate',mobile:'+91 9811111111',creditEnabled:false})})).status).toBe(409);const byName:any=await (await call(`/v1/shops/${x.shop.id}/customers?q=Rah&limit=1`,{headers:auth(x.owner.data.accessToken)})).json();expect(byName.items).toHaveLength(1);const byPhone:any=await (await call(`/v1/shops/${x.shop.id}/customers?q=981111`,{headers:auth(x.owner.data.accessToken)})).json();expect(byPhone.items[0].shop_customer_id).toBe(c.shopCustomerId);expect((await call(`/v1/shops/${x.shop.id}/customers/${c.shopCustomerId}`,{headers:auth(x.owner.data.accessToken)})).status).toBe(200);const updated=await call(`/v1/shops/${x.shop.id}/customers/${c.shopCustomerId}`,{method:'PUT',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),version:1,name:'Rahul Kumar',mobile:'+919811111111',creditEnabled:true,creditLimitPaise:120000})});expect(updated.status).toBe(200);expect((await call(`/v1/shops/${x.shop.id}/customers/${c.shopCustomerId}`,{method:'DELETE',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID()})})).status).toBe(200)});
 it('allows same phone in different shops and rejects cross-shop private access',async()=>{const a=await setup('+919933000002'),b=await setup('+919933000003'),ca=await customer(a,'+919822222222'),cb=await customer(b,'+919822222222');expect(ca.r.status).toBe(201);expect(cb.r.status).toBe(201);expect((await call(`/v1/shops/${a.shop.id}/customers/${ca.c.shopCustomerId}`,{headers:auth(b.owner.data.accessToken)})).status).toBe(403);expect((await call(`/v1/shops/${b.shop.id}/customers/${ca.c.shopCustomerId}`,{headers:auth(b.owner.data.accessToken)})).status).toBe(404)});
 it('adds credit, receives payment, enforces limits/overpayment and idempotency',async()=>{const x=await setup('+919933000004'),{c}=await customer(x,null,100000),credit={mutationId:crypto.randomUUID(),amountPaise:50000,note:'Opening'};expect((await call(`/v1/shops/${x.shop.id}/customers/${c.shopCustomerId}/credit`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify(credit)})).status).toBe(201);expect((await call(`/v1/shops/${x.shop.id}/customers/${c.shopCustomerId}/credit`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify(credit)})).status).toBe(200);await call(`/v1/shops/${x.shop.id}/customers/${c.shopCustomerId}/credit`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),amountPaise:20000})});const pay={mutationId:crypto.randomUUID(),amountPaise:30000,note:'Cash'};expect((await call(`/v1/shops/${x.shop.id}/customers/${c.shopCustomerId}/payment`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify(pay)})).status).toBe(201);expect((await call(`/v1/shops/${x.shop.id}/customers/${c.shopCustomerId}/payment`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify(pay)})).status).toBe(200);const profile:any=await (await call(`/v1/shops/${x.shop.id}/customers/${c.shopCustomerId}`,{headers:auth(x.owner.data.accessToken)})).json();expect(profile.current_balance_paise).toBe(40000);expect((await call(`/v1/shops/${x.shop.id}/customers/${c.shopCustomerId}/payment`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),amountPaise:50000})})).status).toBe(409);expect((await call(`/v1/shops/${x.shop.id}/customers/${c.shopCustomerId}/credit`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),amountPaise:70000})})).status).toBe(409);expect((await call(`/v1/shops/${x.shop.id}/customers/${c.shopCustomerId}/credit`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),amountPaise:-1})})).status).toBe(400)});
 it('supports immutable adjustments and ledger reconciliation/ordering',async()=>{const x=await setup('+919933000005'),{c}=await customer(x,null,200000);for(const [type,amount] of [['ADJUSTMENT_CREDIT',50000],['ADJUSTMENT_DEBIT',20000],['ADJUSTMENT_CREDIT',70000],['ADJUSTMENT_DEBIT',40000]] as const)expect((await call(`/v1/shops/${x.shop.id}/customers/${c.shopCustomerId}/adjustment`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),type,amountPaise:amount,note:'Correction'})})).status).toBe(201);const statement:any=await (await call(`/v1/shops/${x.shop.id}/customers/${c.shopCustomerId}/statement`,{headers:auth(x.owner.data.accessToken)})).json();expect(statement.items).toHaveLength(4);const net=statement.items.reduce((n:number,t:any)=>n+(t.type.endsWith('CREDIT')?t.amount_paise:-t.amount_paise),0);const current:any=await env.DB.prepare('SELECT current_balance_paise FROM shop_customers WHERE id=?').bind(c.shopCustomerId).first();expect(net).toBe(60000);expect(current.current_balance_paise).toBe(60000);expect(statement.items.map((t:any)=>t.balance_after_paise)).toEqual(expect.arrayContaining([50000,30000,100000,60000]))});
 it('rejects cross-shop credit and payment',async()=>{const a=await setup('+919933000006'),b=await setup('+919933000007'),{c}=await customer(a);for(const path of ['credit','payment'])expect((await call(`/v1/shops/${a.shop.id}/customers/${c.shopCustomerId}/${path}`,{method:'POST',headers:auth(b.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),amountPaise:100})})).status).toBe(403)});
 it('executes concurrent payment safely',async()=>{const x=await setup('+919933000008'),{c}=await customer(x,null,100000);await call(`/v1/shops/${x.shop.id}/customers/${c.shopCustomerId}/credit`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),amountPaise:50000})});const send=()=>call(`/v1/shops/${x.shop.id}/customers/${c.shopCustomerId}/payment`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),amountPaise:40000})});const results=await Promise.all([send(),send()]);expect(results.filter(r=>r.status<300)).toHaveLength(1);expect((await env.DB.prepare('SELECT current_balance_paise FROM shop_customers WHERE id=?').bind(c.shopCustomerId).first<any>())!.current_balance_paise).toBe(10000)});
 it('keeps paid sale unchanged and atomically creates credit sale, stock and linked ledger',async()=>{const x=await setup('+919933000009'),{c}=await customer(x,null,100000),p:any=await (await call(`/v1/shops/${x.shop.id}/products`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),name:'Milk',barcode:'8903000000009',unit:'piece',sellingPricePaise:20000,openingStockMilli:10000,minimumStockMilli:0})})).json();const paid:any=await (await call(`/v1/shops/${x.shop.id}/sales`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),items:[{shopProductId:p.shopProductId,quantityMilli:1000}]})})).json();expect(paid.paymentType).toBe('PAID');const mutation=crypto.randomUUID(),credit:any=await (await call(`/v1/shops/${x.shop.id}/sales`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:mutation,paymentType:'CREDIT',shopCustomerId:c.shopCustomerId,items:[{shopProductId:p.shopProductId,quantityMilli:1000}]})})).json();expect(credit.paymentType).toBe('CREDIT');expect((await env.DB.prepare('SELECT current_balance_paise FROM shop_customers WHERE id=?').bind(c.shopCustomerId).first<any>())!.current_balance_paise).toBe(20000);expect((await env.DB.prepare('SELECT stock_quantity_milli FROM shop_products WHERE id=?').bind(p.shopProductId).first<any>())!.stock_quantity_milli).toBe(8000);const tx:any=await env.DB.prepare("SELECT reference_type,reference_id,balance_after_paise FROM credit_transactions WHERE shop_customer_id=? AND type='CREDIT_SALE'").bind(c.shopCustomerId).first();expect(tx.reference_type).toBe('SALE');expect(tx.reference_id).toBe(credit.saleId);expect((await call(`/v1/shops/${x.shop.id}/sales`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:mutation,paymentType:'CREDIT',shopCustomerId:c.shopCustomerId,items:[{shopProductId:p.shopProductId,quantityMilli:1000}]})})).status).toBe(200)});
 it('rejects credit sale entirely on credit limit or stock failure',async()=>{const x=await setup('+919933000010'),{c}=await customer(x,null,10000),p:any=await (await call(`/v1/shops/${x.shop.id}/products`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),name:'Costly',barcode:'8903000000010',unit:'piece',sellingPricePaise:20000,openingStockMilli:1000,minimumStockMilli:0})})).json();const sale=()=>call(`/v1/shops/${x.shop.id}/sales`,{method:'POST',headers:auth(x.owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),paymentType:'CREDIT',shopCustomerId:c.shopCustomerId,items:[{shopProductId:p.shopProductId,quantityMilli:1000}]})});expect((await sale()).status).toBe(409);expect((await env.DB.prepare('SELECT stock_quantity_milli FROM shop_products WHERE id=?').bind(p.shopProductId).first<any>())!.stock_quantity_milli).toBe(1000);expect((await env.DB.prepare('SELECT count(*) c FROM sales WHERE shop_customer_id=?').bind(c.shopCustomerId).first<any>())!.c).toBe(0)});
});

describe('Phase 3 local marketplace',()=>{
 async function marketSetup(phone:string,barcode:string,stock=10000,price=2000){const owner=await register(phone,'1234','SHOPKEEPER');const shop:any=await (await call('/v1/shops',{method:'POST',headers:auth(owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),name:'Market Shop',ownerName:'Owner',addressLine:'1 Road',locality:'Market',city:'Delhi',pincode:'110001',category:'Kirana',latitude:28.6,longitude:77.2})})).json();await env.DB.prepare("UPDATE shops SET status='ACTIVE',is_published=1,accepts_online_orders=1 WHERE id=?").bind(shop.id).run();await env.DB.prepare('UPDATE shop_delivery_settings SET delivery_enabled=1,radius_m=5000,minimum_order_paise=0,delivery_fee_paise=2000,free_delivery_threshold_paise=NULL WHERE shop_id=?').bind(shop.id).run();const slug:any=await env.DB.prepare('SELECT public_slug FROM shops WHERE id=?').bind(shop.id).first();const p:any=await (await call(`/v1/shops/${shop.id}/products`,{method:'POST',headers:auth(owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),name:`Item ${barcode}`,brand:'Brand',barcode,unit:'piece',sellingPricePaise:price,openingStockMilli:stock,minimumStockMilli:0,isAvailable:true})})).json();return{owner,shop,slug:slug.public_slug,p}}
 async function customerUser(phone:string,lat=28.6,lng=77.2){const c=await register(phone,'1234','CUSTOMER');const addressId=crypto.randomUUID(),t=Math.floor(Date.now()/1000);await env.DB.prepare('INSERT INTO addresses(id,user_id,recipient_name,mobile_e164,address_line,locality,city,pincode,latitude,longitude,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(addressId,c.data.userId,'Cust',phone,'1 Road','Market','Delhi','110001',lat,lng,t,t).run();return{...c,addressId}}
 const orderBody=(shopId:string,shopProductId:string,addressId:string|null,qty=2000,extra:any={})=>({mutationId:crypto.randomUUID(),shopId,fulfillmentType:'DELIVERY',addressId,items:[{shopProductId,quantityMilli:qty}],...extra});
 const reserved=async(shopProductId:string)=>(await env.DB.prepare('SELECT stock_quantity_milli,reserved_quantity_milli FROM shop_products WHERE id=?').bind(shopProductId).first<any>());
 const advance=(shopId:string,token:string,orderId:string,status:string)=>call(`/v1/shops/${shopId}/orders/${orderId}/status`,{method:'POST',headers:auth(token),body:JSON.stringify({mutationId:crypto.randomUUID(),status})});
 it('discovers nearby published shops and excludes unpublished or distant shops',async()=>{const x=await marketSetup('+919944000001','8904000000001'),cust=await customerUser('+919944000002');const near:any=await (await call('/v1/market/shops?latitude=28.6&longitude=77.2&radiusM=5000',{headers:auth(cust.data.accessToken)})).json();expect(near.items.map((s:any)=>s.id)).toContain(x.shop.id);expect(near.items.find((s:any)=>s.id===x.shop.id).distance_m).toBeLessThan(1000);const far:any=await (await call('/v1/market/shops?latitude=19.07&longitude=72.87&radiusM=5000',{headers:auth(cust.data.accessToken)})).json();expect(far.items.map((s:any)=>s.id)).not.toContain(x.shop.id);expect((await call('/v1/market/shops?latitude=28.6&longitude=77.2')).status).toBe(401);await env.DB.prepare('UPDATE shops SET is_published=0 WHERE id=?').bind(x.shop.id).run();const hidden:any=await (await call('/v1/market/shops?latitude=28.6&longitude=77.2',{headers:auth(cust.data.accessToken)})).json();expect(hidden.items.map((s:any)=>s.id)).not.toContain(x.shop.id)});
 it('serves a public shop page with catalogue only for a published shop',async()=>{const x=await marketSetup('+919944000003','8904000000003'),cust=await customerUser('+919944000004');const page:any=await (await call(`/v1/market/shops/${x.slug}`,{headers:auth(cust.data.accessToken)})).json();expect(page.shop.id).toBe(x.shop.id);expect(page.shop).not.toHaveProperty('pin_hash');expect(page.items).toHaveLength(1);expect(page.items[0].shop_product_id).toBe(x.p.shopProductId);expect((await call('/v1/market/shops/does-not-exist',{headers:auth(cust.data.accessToken)})).status).toBe(404)});
 it('creates an order with server prices, reserves stock and is idempotent',async()=>{const x=await marketSetup('+919944000005','8904000000005',10000,2000),cust=await customerUser('+919944000006');const body=orderBody(x.shop.id,x.p.shopProductId,cust.addressId,2000);const r=await call('/v1/orders',{method:'POST',headers:auth(cust.data.accessToken),body:JSON.stringify(body)}),o:any=await r.json();expect(r.status).toBe(201);expect(o.subtotalPaise).toBe(4000);expect(o.deliveryFeePaise).toBe(2000);expect(o.totalPaise).toBe(6000);expect(o.status).toBe('PENDING');expect((await reserved(x.p.shopProductId)).reserved_quantity_milli).toBe(2000);expect((await reserved(x.p.shopProductId)).stock_quantity_milli).toBe(10000);const replay=await call('/v1/orders',{method:'POST',headers:auth(cust.data.accessToken),body:JSON.stringify(body)});expect(replay.status).toBe(200);expect((await replay.json() as any).orderId).toBe(o.orderId);expect((await env.DB.prepare('SELECT count(*) c FROM orders WHERE customer_user_id=?').bind(cust.data.userId).first<any>())!.c).toBe(1);const mine:any=await (await call('/v1/orders',{headers:auth(cust.data.accessToken)})).json();expect(mine.items).toHaveLength(1);expect((await call(`/v1/orders/${o.orderId}`,{headers:auth(cust.data.accessToken)})).status).toBe(200);const other=await register('+919944000007');expect((await call(`/v1/orders/${o.orderId}`,{headers:auth(other.data.accessToken)})).status).toBe(403)});
 it('rejects minimum, range, delivery-disabled and insufficient-stock orders',async()=>{const x=await marketSetup('+919944000008','8904000000008',1000,1000),cust=await customerUser('+919944000009');await env.DB.prepare('UPDATE shop_delivery_settings SET minimum_order_paise=100000 WHERE shop_id=?').bind(x.shop.id).run();expect((await call('/v1/orders',{method:'POST',headers:auth(cust.data.accessToken),body:JSON.stringify(orderBody(x.shop.id,x.p.shopProductId,cust.addressId,1000))})).status).toBe(409);await env.DB.prepare('UPDATE shop_delivery_settings SET minimum_order_paise=0 WHERE shop_id=?').bind(x.shop.id).run();const farCust=await customerUser('+919944000010',19.07,72.87);expect((await call('/v1/orders',{method:'POST',headers:auth(farCust.data.accessToken),body:JSON.stringify(orderBody(x.shop.id,x.p.shopProductId,farCust.addressId,1000))})).status).toBe(409);await env.DB.prepare('UPDATE shop_delivery_settings SET delivery_enabled=0 WHERE shop_id=?').bind(x.shop.id).run();expect((await call('/v1/orders',{method:'POST',headers:auth(cust.data.accessToken),body:JSON.stringify(orderBody(x.shop.id,x.p.shopProductId,cust.addressId,1000))})).status).toBe(409);await env.DB.prepare('UPDATE shop_delivery_settings SET delivery_enabled=1 WHERE shop_id=?').bind(x.shop.id).run();expect((await call('/v1/orders',{method:'POST',headers:auth(cust.data.accessToken),body:JSON.stringify(orderBody(x.shop.id,x.p.shopProductId,cust.addressId,5000))})).status).toBe(409);expect((await reserved(x.p.shopProductId)).reserved_quantity_milli).toBe(0)});
 it('enforces shopkeeper transitions, releases reservation on reject, and decrements stock with ledger on delivery',async()=>{const x=await marketSetup('+919944000011','8904000000111',10000,2000),cust=await customerUser('+919944000012'),other=await marketSetup('+919944000013','8904000000131'),o:any=await (await call('/v1/orders',{method:'POST',headers:auth(cust.data.accessToken),body:JSON.stringify(orderBody(x.shop.id,x.p.shopProductId,cust.addressId,2000))})).json();expect((await advance(x.shop.id,other.owner.data.accessToken,o.orderId,'ACCEPTED')).status).toBe(403);expect((await advance(x.shop.id,x.owner.data.accessToken,o.orderId,'DELIVERED')).status).toBe(409);expect((await advance(x.shop.id,x.owner.data.accessToken,o.orderId,'ACCEPTED')).status).toBe(200);expect((await advance(x.shop.id,x.owner.data.accessToken,o.orderId,'PACKING')).status).toBe(200);expect((await advance(x.shop.id,x.owner.data.accessToken,o.orderId,'READY')).status).toBe(200);expect((await advance(x.shop.id,x.owner.data.accessToken,o.orderId,'OUT_FOR_DELIVERY')).status).toBe(200);expect((await advance(x.shop.id,x.owner.data.accessToken,o.orderId,'DELIVERED')).status).toBe(200);const after=await reserved(x.p.shopProductId);expect(after.stock_quantity_milli).toBe(8000);expect(after.reserved_quantity_milli).toBe(0);const tx:any=await env.DB.prepare("SELECT type,quantity_delta_milli,reference_type,reference_id FROM inventory_transactions WHERE shop_product_id=? AND type='SALE'").bind(x.p.shopProductId).first();expect(tx).toEqual(expect.objectContaining({type:'SALE',quantity_delta_milli:-2000,reference_type:'ORDER',reference_id:o.orderId}));const list:any=await (await call(`/v1/shops/${x.shop.id}/orders`,{headers:auth(x.owner.data.accessToken)})).json();expect(list.items[0].status).toBe('DELIVERED');const rejected:any=await (await call('/v1/orders',{method:'POST',headers:auth(cust.data.accessToken),body:JSON.stringify(orderBody(x.shop.id,x.p.shopProductId,cust.addressId,2000))})).json();expect((await advance(x.shop.id,x.owner.data.accessToken,rejected.orderId,'REJECTED')).status).toBe(200);expect((await reserved(x.p.shopProductId)).reserved_quantity_milli).toBe(0)});
 it('lets a customer cancel a pending order and blocks cancel after acceptance beyond PENDING/ACCEPTED',async()=>{const x=await marketSetup('+919944000014','8904000000141',10000,2000),cust=await customerUser('+919944000015'),o:any=await (await call('/v1/orders',{method:'POST',headers:auth(cust.data.accessToken),body:JSON.stringify(orderBody(x.shop.id,x.p.shopProductId,cust.addressId,2000))})).json();const cancelBody={mutationId:crypto.randomUUID()};expect((await call(`/v1/orders/${o.orderId}/cancel`,{method:'POST',headers:auth(cust.data.accessToken),body:JSON.stringify(cancelBody)})).status).toBe(200);expect((await reserved(x.p.shopProductId)).reserved_quantity_milli).toBe(0);expect((await call(`/v1/orders/${o.orderId}/cancel`,{method:'POST',headers:auth(cust.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID()})})).status).toBe(409);const other=await register('+919944000016');expect((await call(`/v1/orders/${o.orderId}/cancel`,{method:'POST',headers:auth(other.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID()})})).status).toBe(404)});
 it('keeps order item snapshots immutable after catalogue changes',async()=>{const x=await marketSetup('+919944000017','8904000000171',10000,2000),cust=await customerUser('+919944000018'),o:any=await (await call('/v1/orders',{method:'POST',headers:auth(cust.data.accessToken),body:JSON.stringify(orderBody(x.shop.id,x.p.shopProductId,cust.addressId,3000))})).json();await env.DB.prepare("UPDATE products SET name='Renamed' WHERE id=?").bind(x.p.productId).run();await env.DB.prepare('UPDATE shop_products SET selling_price_paise=9999 WHERE id=?').bind(x.p.shopProductId).run();const detail:any=await (await call(`/v1/orders/${o.orderId}`,{headers:auth(cust.data.accessToken)})).json();expect(detail.items[0].product_name_snapshot).not.toBe('Renamed');expect(detail.items[0].unit_price_paise).toBe(2000);expect(detail.history.map((h:any)=>h.status)).toEqual(['PENDING'])});
});

describe('customer credit visibility',()=>{
 it('shows customers their own udhaar balance and entries and hides other users data',async()=>{const owner=await register('+919955500001','1234','SHOPKEEPER'),shop:any=await (await call('/v1/shops',{method:'POST',headers:auth(owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),name:'Udhaar Shop',ownerName:'Owner',addressLine:'1 Road',locality:'Market',city:'Delhi',pincode:'110001',category:'Kirana',latitude:28.6,longitude:77.2})})).json();const prod:any=await (await call(`/v1/shops/${shop.id}/products`,{method:'POST',headers:auth(owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),name:'Chawal',unit:'kg',sellingPricePaise:6000,openingStockMilli:20000,minimumStockMilli:1000,isAvailable:true})})).json();const cust=await register('+919955500002','1234','CUSTOMER');const sc:any=await (await call(`/v1/shops/${shop.id}/customers`,{method:'POST',headers:auth(owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),name:'Ramesh',mobile:'+919955500002',creditEnabled:true,creditLimitPaise:50000})})).json();const sale=await call(`/v1/shops/${shop.id}/sales`,{method:'POST',headers:auth(owner.data.accessToken),body:JSON.stringify({mutationId:crypto.randomUUID(),paymentType:'CREDIT',shopCustomerId:sc.shopCustomerId,items:[{shopProductId:prod.shopProductId,quantityMilli:2000}]})});expect(sale.status).toBe(201);const mine=await call('/v1/my/credit',{headers:auth(cust.data.accessToken)});expect(mine.status).toBe(200);const data:any=await mine.json();expect(data.items).toHaveLength(1);expect(data.items[0].shop_id).toBe(shop.id);expect(data.items[0].balance_paise).toBe(12000);expect(data.recent).toHaveLength(1);expect(data.recent[0].type).toBe('CREDIT_SALE');const other=await register('+919955500003','1234','CUSTOMER');const hidden:any=await (await call('/v1/my/credit',{headers:auth(other.data.accessToken)})).json();expect(hidden.items).toHaveLength(0);expect((await call('/v1/my/credit')).status).toBe(401)});
});
