package `in`.localdukaan.core.database
import android.content.Context
import androidx.room.*
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase
import kotlinx.coroutines.flow.Flow
@Entity(tableName="local_profile") data class LocalProfile(@PrimaryKey val userId:String,val name:String,val language:String,val customer:Boolean,val shopkeeper:Boolean,val synced:Boolean)
@Entity(tableName="local_shop") data class LocalShop(@PrimaryKey val id:String,val name:String,val city:String,val locality:String,val status:String,val synced:Boolean,val ownerName:String="",val phone:String?=null,val addressLine:String="",val pincode:String="",val description:String?=null,val publicSlug:String?=null,val isPublished:Boolean=false,val version:Long=1)
@Entity(tableName="products",indices=[Index("barcode")]) data class ProductEntity(@PrimaryKey val id:String,val barcode:String?,val name:String,val brand:String?,val unit:String,val description:String?,val updatedAt:Long,val category:String?=null)
@Entity(tableName="shop_products",indices=[Index("shopId"),Index("productId"),Index(value=["shopId","productId"],unique=true)]) data class ShopProductEntity(@PrimaryKey val id:String,val shopId:String,val productId:String,val sellingPricePaise:Long,val stockQuantityMilli:Long,val reservedQuantityMilli:Long,val minimumStockMilli:Long,val isAvailable:Boolean,val isArchived:Boolean,val imageKey:String?,val version:Long,val syncState:String,val updatedAt:Long,val costPricePaise:Long=0)
@Entity(tableName="inventory_transactions",indices=[Index("shopId"),Index("shopProductId"),Index(value=["shopId","mutationId"],unique=true)]) data class InventoryTransactionEntity(@PrimaryKey val id:String,val shopId:String,val shopProductId:String,val type:String,val quantityDeltaMilli:Long,val stockAfterMilli:Long,val mutationId:String,val createdAt:Long)
@Entity(tableName="sales",indices=[Index("shopId"),Index("createdAt"),Index("shopCustomerId")]) data class SaleEntity(@PrimaryKey val id:String,val shopId:String,val totalPaise:Long,val itemCount:Int,val status:String,val mutationId:String,val createdAt:Long,val shopCustomerId:String?=null,val paymentType:String="PAID",val creditAmountPaise:Long=0,val paymentMethod:String="CASH",val discountPaise:Long=0,val subtotalPaise:Long=0,val customerName:String?=null)
@Entity(tableName="sale_items",indices=[Index("saleId"),Index("shopProductId")]) data class SaleItemEntity(@PrimaryKey val id:String,val saleId:String,val shopProductId:String,val productName:String,val unit:String,val unitPricePaise:Long,val quantityMilli:Long,val lineTotalPaise:Long,val costPricePaise:Long=0)
@Entity(tableName="customers") data class CustomerEntity(@PrimaryKey val id:String,val name:String,val normalizedPhone:String?,val updatedAt:Long)
@Entity(tableName="shop_customers",indices=[Index("shopId"),Index("customerId"),Index(value=["shopId","normalizedPhone"],unique=true)]) data class ShopCustomerEntity(@PrimaryKey val id:String,val shopId:String,val customerId:String,val displayName:String,val normalizedPhone:String?,val notes:String?,val creditEnabled:Boolean,val creditLimitPaise:Long?,val currentBalancePaise:Long,val isArchived:Boolean,val version:Long,val syncState:String,val updatedAt:Long){val availableCreditPaise:Long? get()=if(creditEnabled&&creditLimitPaise!=null)(creditLimitPaise-currentBalancePaise).coerceAtLeast(0) else null}
@Entity(tableName="credit_transactions",indices=[Index("shopId"),Index("shopCustomerId"),Index("createdAt"),Index(value=["shopId","mutationId"],unique=true)]) data class CreditTransactionEntity(@PrimaryKey val id:String,val shopId:String,val shopCustomerId:String,val type:String,val amountPaise:Long,val balanceAfterPaise:Long,val referenceType:String?,val referenceId:String?,val note:String?,val mutationId:String,val status:String,val createdAt:Long)
@Entity(tableName="purchase_list",indices=[Index("shopId"),Index(value=["shopId","shopProductId"],unique=true)]) data class PurchaseListEntity(@PrimaryKey val id:String,val shopId:String,val shopProductId:String,val productName:String,val quantityMilli:Long,val isPurchased:Boolean,val version:Long,val syncState:String,val updatedAt:Long)
@Entity(tableName="outbox") data class Outbox(@PrimaryKey val mutationId:String,val operation:String,val payload:String,val state:String="PENDING",val createdAt:Long=System.currentTimeMillis(),val attempts:Int=0,val lastError:String?=null)
data class ProductRow(@Embedded val shopProduct:ShopProductEntity,@Relation(parentColumn="productId",entityColumn="id") val product:ProductEntity){val lowStock:Boolean get()=shopProduct.stockQuantityMilli<=shopProduct.minimumStockMilli;val profitMarginPaise:Long get()=shopProduct.sellingPricePaise-shopProduct.costPricePaise}
data class DailySaleRow(val epochDay:Long,val salesPaise:Long,val creditPaise:Long,val bills:Int)
data class DailyProfitRow(val epochDay:Long,val profitPaise:Long,val itemsSoldMilli:Long)
data class StockValueRow(val totalStockValuePaise:Long,val totalItems:Int,val lowCount:Int)
@Dao interface LocalDao {
 @Query("SELECT * FROM local_profile LIMIT 1") fun profile():Flow<LocalProfile?>
 @Insert(onConflict=OnConflictStrategy.REPLACE) suspend fun putProfile(v:LocalProfile)
 @Query("SELECT * FROM local_shop ORDER BY name") fun shops():Flow<List<LocalShop>>
 @Insert(onConflict=OnConflictStrategy.REPLACE) suspend fun putShop(v:LocalShop)
 @Transaction @Query("SELECT * FROM shop_products WHERE shopId=:shopId AND isArchived=0 ORDER BY updatedAt DESC") fun products(shopId:String):Flow<List<ProductRow>>
 @Transaction @Query("SELECT sp.* FROM shop_products sp JOIN products p ON p.id=sp.productId WHERE sp.shopId=:shopId AND p.barcode=:barcode AND sp.isArchived=0 LIMIT 1") suspend fun productByBarcode(shopId:String,barcode:String):ProductRow?
 @Query("SELECT * FROM products WHERE barcode IN (:codes) LIMIT 1") suspend fun catalogueByBarcode(codes:List<String>):ProductEntity?
 @Query("SELECT * FROM inventory_transactions WHERE shopId=:shopId AND shopProductId=:shopProductId ORDER BY createdAt DESC") fun inventory(shopId:String,shopProductId:String):Flow<List<InventoryTransactionEntity>>
 @Query("SELECT * FROM sales WHERE shopId=:shopId ORDER BY createdAt DESC") fun sales(shopId:String):Flow<List<SaleEntity>>
 @Query("SELECT * FROM sales WHERE mutationId=:mutation LIMIT 1") fun saleByMutation(mutation:String):SaleEntity?
 @Query("SELECT * FROM sale_items WHERE saleId=:saleId") suspend fun saleItems(saleId:String):List<SaleItemEntity>
 @Query("DELETE FROM sales WHERE id=:id") fun deleteSale(id:String)
 @Query("DELETE FROM sale_items WHERE saleId=:saleId") fun deleteSaleItems(saleId:String)
 @Query("SELECT * FROM purchase_list WHERE shopId=:shopId ORDER BY isPurchased,updatedAt DESC") fun purchaseList(shopId:String):Flow<List<PurchaseListEntity>>
 @Query("SELECT * FROM shop_customers WHERE shopId=:shopId AND isArchived=0 ORDER BY displayName") fun customers(shopId:String):Flow<List<ShopCustomerEntity>>
 @Query("SELECT * FROM credit_transactions WHERE shopId=:shopId AND shopCustomerId=:customerId ORDER BY createdAt DESC") fun creditStatement(shopId:String,customerId:String):Flow<List<CreditTransactionEntity>>
 @Query("SELECT createdAt/86400000 AS epochDay, SUM(totalPaise) AS salesPaise, SUM(creditAmountPaise) AS creditPaise, SUM(CASE WHEN status!='REJECTED' THEN 1 ELSE 0 END) AS bills FROM sales WHERE shopId=:shopId GROUP BY epochDay ORDER BY epochDay DESC LIMIT 30") fun dailySales(shopId:String):Flow<List<DailySaleRow>>
 @Query("SELECT s.createdAt/86400000 AS epochDay, SUM(si.lineTotalPaise - (si.quantityMilli*sp.costPricePaise)/1000) AS profitPaise, SUM(si.quantityMilli) AS itemsSoldMilli FROM sale_items si JOIN sales s ON s.id=si.saleId JOIN shop_products sp ON sp.id=si.shopProductId WHERE s.shopId=:shopId GROUP BY epochDay ORDER BY epochDay DESC LIMIT 30") fun dailyProfit(shopId:String):Flow<List<DailyProfitRow>>
 @Query("SELECT COALESCE(SUM(stockQuantityMilli*costPricePaise)/1000,0) AS totalStockValuePaise, COUNT(*) AS totalItems, SUM(CASE WHEN stockQuantityMilli<=minimumStockMilli THEN 1 ELSE 0 END) AS lowCount FROM shop_products WHERE shopId=:shopId AND isArchived=0") fun stockValue(shopId:String):Flow<StockValueRow?>
 @Query("SELECT COALESCE(SUM(totalPaise),0) FROM sales WHERE shopId=:shopId AND status!='REJECTED'") suspend fun totalSales(shopId:String):Long
@Query("SELECT COUNT(*) FROM shop_customers WHERE shopId=:shopId AND isArchived=0 AND currentBalancePaise>0") suspend fun dueCount(shopId:String):Int
 @Query("SELECT COALESCE(SUM(si.lineTotalPaise - (si.quantityMilli*sp.costPricePaise)/1000),0) FROM sale_items si JOIN sales s ON s.id=si.saleId JOIN shop_products sp ON sp.id=si.shopProductId WHERE s.shopId=:shopId AND s.status='COMPLETED' AND s.createdAt>=:since") suspend fun profitSince(shopId:String,since:Long):Long
 @Query("SELECT COALESCE(SUM(si.quantityMilli*sp.costPricePaise)/1000,0) FROM sale_items si JOIN sales s ON s.id=si.saleId JOIN shop_products sp ON sp.id=si.shopProductId WHERE s.shopId=:shopId AND s.status='COMPLETED' AND s.createdAt>=:since") suspend fun costSince(shopId:String,since:Long):Long
 @Query("SELECT * FROM sales WHERE shopId=:shopId AND status!='REJECTED' AND createdAt>=:since ORDER BY createdAt DESC LIMIT 100") suspend fun salesSince(shopId:String,since:Long):List<SaleEntity>
 @Query("SELECT COALESCE(SUM(currentBalancePaise),0) FROM shop_customers WHERE shopId=:shopId AND isArchived=0") suspend fun totalDue(shopId:String):Long
 @Insert(onConflict=OnConflictStrategy.REPLACE) suspend fun putProduct(v:ProductEntity)
 @Insert(onConflict=OnConflictStrategy.REPLACE) suspend fun putShopProduct(v:ShopProductEntity)
 @Insert(onConflict=OnConflictStrategy.IGNORE) suspend fun putInventory(v:InventoryTransactionEntity)
 @Insert(onConflict=OnConflictStrategy.REPLACE) suspend fun putSale(v:SaleEntity)
 @Insert(onConflict=OnConflictStrategy.REPLACE) suspend fun putSaleItems(v:List<SaleItemEntity>)
 @Query("UPDATE sales SET id=:serverId,status='COMPLETED' WHERE mutationId=:mutationId") suspend fun completeSale(mutationId:String,serverId:String)
 @Query("UPDATE sale_items SET saleId=:serverId WHERE saleId=:localId") suspend fun remapSaleItems(localId:String,serverId:String)
 @Query("UPDATE sales SET shopCustomerId=:newId WHERE shopCustomerId=:oldId") suspend fun remapSaleCustomer(oldId:String,newId:String)
 @Query("UPDATE sales SET status='REJECTED' WHERE mutationId=:mutationId") suspend fun rejectSale(mutationId:String)
 @Insert(onConflict=OnConflictStrategy.REPLACE) suspend fun putCustomer(v:CustomerEntity)
 @Insert(onConflict=OnConflictStrategy.REPLACE) suspend fun putShopCustomer(v:ShopCustomerEntity)
 @Insert(onConflict=OnConflictStrategy.REPLACE) suspend fun putCredit(v:CreditTransactionEntity)
 @Query("UPDATE shop_customers SET currentBalancePaise=:balance,syncState=:state,version=:version WHERE id=:id") suspend fun setCreditBalance(id:String,balance:Long,state:String,version:Long)
 @Insert(onConflict=OnConflictStrategy.REPLACE) suspend fun putPurchaseItem(v:PurchaseListEntity)
 @Query("DELETE FROM purchase_list WHERE id=:id") suspend fun deletePurchaseItem(id:String)
 @Query("UPDATE shop_products SET isArchived=1,isAvailable=0,syncState='PENDING' WHERE id=:id") suspend fun archiveProduct(id:String)
 @Query("DELETE FROM shop_products WHERE id=:id") suspend fun deleteShopProduct(id:String)
 @Query("DELETE FROM products WHERE id=:id") suspend fun deleteProduct(id:String)
 @Query("DELETE FROM inventory_transactions WHERE id=:id") suspend fun deleteInventory(id:String)
 @Insert(onConflict=OnConflictStrategy.REPLACE) suspend fun enqueue(v:Outbox)
 @Query("SELECT * FROM outbox WHERE state='PENDING' ORDER BY createdAt LIMIT 50") suspend fun pending():List<Outbox>
 @Query("DELETE FROM outbox WHERE mutationId=:id") suspend fun ack(id:String)
 @Query("UPDATE outbox SET attempts=attempts+1,lastError=:error WHERE mutationId=:id") suspend fun fail(id:String,error:String)
 @Query("UPDATE outbox SET state='FAILED',attempts=attempts+1,lastError=:error WHERE mutationId=:id") suspend fun failPermanent(id:String,error:String)
 @Query("UPDATE outbox SET payload=replace(payload,:oldId,:newId) WHERE state='PENDING'") suspend fun replacePendingProductId(oldId:String,newId:String)
 @Query("UPDATE shop_products SET imageKey=:key,syncState=:state,version=CASE WHEN :version IS NULL THEN version ELSE :version END WHERE id=:id") suspend fun setProductImage(id:String,key:String?,state:String,version:Long?=null)
 @Query("UPDATE shop_products SET stockQuantityMilli=stockQuantityMilli+:delta,syncState='PENDING' WHERE id=:id AND stockQuantityMilli+:delta>=reservedQuantityMilli") suspend fun adjustLocalStock(id:String,delta:Long):Int
 @Query("UPDATE shop_products SET stockQuantityMilli=:stock,syncState='SYNCED',version=version+1 WHERE id=:id") suspend fun setCanonicalStock(id:String,stock:Long)
 @Query("SELECT * FROM shop_customers WHERE id=:id LIMIT 1") suspend fun shopCustomer(id:String):ShopCustomerEntity?
 @Query("UPDATE shop_customers SET isArchived=1,syncState='PENDING' WHERE id=:id") suspend fun archiveCustomer(id:String)
 @Query("UPDATE shop_customers SET currentBalancePaise=:balance,syncState=:state WHERE id=:id") suspend fun setCreditBalanceOnly(id:String,balance:Long,state:String)
 @Query("UPDATE credit_transactions SET status='REJECTED' WHERE mutationId=:mutationId") suspend fun rejectCredit(mutationId:String)
 @Query("DELETE FROM shop_customers WHERE id=:id") suspend fun deleteShopCustomer(id:String)
 @Query("DELETE FROM customers WHERE id=:id") suspend fun deleteCustomer(id:String)
 @Query("DELETE FROM credit_transactions WHERE id=:id") suspend fun deleteCredit(id:String)
 @Query("UPDATE outbox SET payload=replace(payload,:oldId,:newId) WHERE state='PENDING'") suspend fun replacePendingId(oldId:String,newId:String)
 @Query("SELECT * FROM shop_products WHERE id=:id LIMIT 1") suspend fun shopProduct(id:String):ShopProductEntity?
 @Query("SELECT * FROM products WHERE id=:id LIMIT 1") suspend fun product(id:String):ProductEntity?
 /** Account-switch isolation: jo shops ab ke user ke NAHI hain, unka saara data mita do (children pehle). */
 @Query("DELETE FROM sale_items WHERE saleId IN (SELECT id FROM sales WHERE shopId NOT IN (:ids))") suspend fun deleteSaleItemsNotInShops(ids:List<String>)
 @Query("DELETE FROM sales WHERE shopId NOT IN (:ids)") suspend fun deleteSalesNotInShops(ids:List<String>)
 @Query("DELETE FROM inventory_transactions WHERE shopId NOT IN (:ids)") suspend fun deleteInventoryNotInShops(ids:List<String>)
 @Query("DELETE FROM credit_transactions WHERE shopId NOT IN (:ids)") suspend fun deleteCreditNotInShops(ids:List<String>)
 @Query("DELETE FROM purchase_list WHERE shopId NOT IN (:ids)") suspend fun deletePurchaseNotInShops(ids:List<String>)
 @Query("DELETE FROM shop_customers WHERE shopId NOT IN (:ids)") suspend fun deleteShopCustomersNotInShops(ids:List<String>)
 @Query("DELETE FROM customers WHERE id NOT IN (SELECT customerId FROM shop_customers)") suspend fun deleteOrphanCustomers()
 @Query("DELETE FROM shop_products WHERE shopId NOT IN (:ids)") suspend fun deleteShopProductsNotInShops(ids:List<String>)
 @Query("DELETE FROM products WHERE id NOT IN (SELECT productId FROM shop_products)") suspend fun deleteOrphanProducts()
 @Query("DELETE FROM local_shop WHERE id NOT IN (:ids)") suspend fun deleteShopsNotIn(ids:List<String>)
}
@Database(entities=[LocalProfile::class,LocalShop::class,ProductEntity::class,ShopProductEntity::class,InventoryTransactionEntity::class,SaleEntity::class,SaleItemEntity::class,CustomerEntity::class,ShopCustomerEntity::class,CreditTransactionEntity::class,PurchaseListEntity::class,Outbox::class],version=6,exportSchema=true)
abstract class LocalDatabase:RoomDatabase(){abstract fun dao():LocalDao
 companion object {val MIGRATION_1_2=object:Migration(1,2){override fun migrate(db:SupportSQLiteDatabase){
  db.execSQL("ALTER TABLE local_shop ADD COLUMN ownerName TEXT NOT NULL DEFAULT ''");db.execSQL("ALTER TABLE local_shop ADD COLUMN phone TEXT");db.execSQL("ALTER TABLE local_shop ADD COLUMN addressLine TEXT NOT NULL DEFAULT ''");db.execSQL("ALTER TABLE local_shop ADD COLUMN pincode TEXT NOT NULL DEFAULT ''");db.execSQL("ALTER TABLE local_shop ADD COLUMN description TEXT");db.execSQL("ALTER TABLE local_shop ADD COLUMN publicSlug TEXT");db.execSQL("ALTER TABLE local_shop ADD COLUMN isPublished INTEGER NOT NULL DEFAULT 0");db.execSQL("ALTER TABLE local_shop ADD COLUMN version INTEGER NOT NULL DEFAULT 1");
  db.execSQL("CREATE TABLE IF NOT EXISTS products (id TEXT NOT NULL PRIMARY KEY, barcode TEXT, name TEXT NOT NULL, brand TEXT, unit TEXT NOT NULL, description TEXT, updatedAt INTEGER NOT NULL)");db.execSQL("CREATE TABLE IF NOT EXISTS shop_products (id TEXT NOT NULL PRIMARY KEY, shopId TEXT NOT NULL, productId TEXT NOT NULL, sellingPricePaise INTEGER NOT NULL, stockQuantityMilli INTEGER NOT NULL, reservedQuantityMilli INTEGER NOT NULL, minimumStockMilli INTEGER NOT NULL, isAvailable INTEGER NOT NULL, isArchived INTEGER NOT NULL, imageKey TEXT, version INTEGER NOT NULL, syncState TEXT NOT NULL, updatedAt INTEGER NOT NULL)");db.execSQL("CREATE INDEX IF NOT EXISTS index_shop_products_shopId ON shop_products(shopId)");db.execSQL("CREATE INDEX IF NOT EXISTS index_shop_products_productId ON shop_products(productId)");db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS index_shop_products_shopId_productId ON shop_products(shopId,productId)");db.execSQL("CREATE TABLE IF NOT EXISTS inventory_transactions (id TEXT NOT NULL PRIMARY KEY, shopId TEXT NOT NULL, shopProductId TEXT NOT NULL, type TEXT NOT NULL, quantityDeltaMilli INTEGER NOT NULL, stockAfterMilli INTEGER NOT NULL, mutationId TEXT NOT NULL, createdAt INTEGER NOT NULL)");db.execSQL("CREATE INDEX IF NOT EXISTS index_inventory_transactions_shopId ON inventory_transactions(shopId)");db.execSQL("CREATE INDEX IF NOT EXISTS index_inventory_transactions_shopProductId ON inventory_transactions(shopProductId)");db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS index_inventory_transactions_shopId_mutationId ON inventory_transactions(shopId,mutationId)");db.execSQL("ALTER TABLE outbox ADD COLUMN attempts INTEGER NOT NULL DEFAULT 0");db.execSQL("ALTER TABLE outbox ADD COLUMN lastError TEXT")}}
 val MIGRATION_2_3=object:Migration(2,3){override fun migrate(db:SupportSQLiteDatabase){db.execSQL("CREATE TABLE IF NOT EXISTS sales (id TEXT NOT NULL PRIMARY KEY, shopId TEXT NOT NULL, totalPaise INTEGER NOT NULL, itemCount INTEGER NOT NULL, status TEXT NOT NULL, mutationId TEXT NOT NULL, createdAt INTEGER NOT NULL)");db.execSQL("CREATE INDEX IF NOT EXISTS index_sales_shopId ON sales(shopId)");db.execSQL("CREATE INDEX IF NOT EXISTS index_sales_createdAt ON sales(createdAt)");db.execSQL("CREATE TABLE IF NOT EXISTS sale_items (id TEXT NOT NULL PRIMARY KEY, saleId TEXT NOT NULL, shopProductId TEXT NOT NULL, productName TEXT NOT NULL, unit TEXT NOT NULL, unitPricePaise INTEGER NOT NULL, quantityMilli INTEGER NOT NULL, lineTotalPaise INTEGER NOT NULL)");db.execSQL("CREATE INDEX IF NOT EXISTS index_sale_items_saleId ON sale_items(saleId)");db.execSQL("CREATE INDEX IF NOT EXISTS index_sale_items_shopProductId ON sale_items(shopProductId)");db.execSQL("CREATE TABLE IF NOT EXISTS purchase_list (id TEXT NOT NULL PRIMARY KEY, shopId TEXT NOT NULL, shopProductId TEXT NOT NULL, productName TEXT NOT NULL, quantityMilli INTEGER NOT NULL, isPurchased INTEGER NOT NULL, version INTEGER NOT NULL, syncState TEXT NOT NULL, updatedAt INTEGER NOT NULL)");db.execSQL("CREATE INDEX IF NOT EXISTS index_purchase_list_shopId ON purchase_list(shopId)");db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS index_purchase_list_shopId_shopProductId ON purchase_list(shopId,shopProductId)")}}
 val MIGRATION_3_4=object:Migration(3,4){override fun migrate(db:SupportSQLiteDatabase){db.execSQL("ALTER TABLE sales ADD COLUMN shopCustomerId TEXT");db.execSQL("ALTER TABLE sales ADD COLUMN paymentType TEXT NOT NULL DEFAULT 'PAID'");db.execSQL("ALTER TABLE sales ADD COLUMN creditAmountPaise INTEGER NOT NULL DEFAULT 0");db.execSQL("CREATE INDEX IF NOT EXISTS index_sales_shopCustomerId ON sales(shopCustomerId)");db.execSQL("CREATE TABLE IF NOT EXISTS customers (id TEXT NOT NULL PRIMARY KEY,name TEXT NOT NULL,normalizedPhone TEXT,updatedAt INTEGER NOT NULL)");db.execSQL("CREATE TABLE IF NOT EXISTS shop_customers (id TEXT NOT NULL PRIMARY KEY,shopId TEXT NOT NULL,customerId TEXT NOT NULL,displayName TEXT NOT NULL,normalizedPhone TEXT,notes TEXT,creditEnabled INTEGER NOT NULL,creditLimitPaise INTEGER,currentBalancePaise INTEGER NOT NULL,isArchived INTEGER NOT NULL,version INTEGER NOT NULL,syncState TEXT NOT NULL,updatedAt INTEGER NOT NULL)");db.execSQL("CREATE INDEX IF NOT EXISTS index_shop_customers_shopId ON shop_customers(shopId)");db.execSQL("CREATE INDEX IF NOT EXISTS index_shop_customers_customerId ON shop_customers(customerId)");db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS index_shop_customers_shopId_normalizedPhone ON shop_customers(shopId,normalizedPhone)");db.execSQL("CREATE TABLE IF NOT EXISTS credit_transactions (id TEXT NOT NULL PRIMARY KEY,shopId TEXT NOT NULL,shopCustomerId TEXT NOT NULL,type TEXT NOT NULL,amountPaise INTEGER NOT NULL,balanceAfterPaise INTEGER NOT NULL,referenceType TEXT,referenceId TEXT,note TEXT,mutationId TEXT NOT NULL,status TEXT NOT NULL,createdAt INTEGER NOT NULL)");db.execSQL("CREATE INDEX IF NOT EXISTS index_credit_transactions_shopId ON credit_transactions(shopId)");db.execSQL("CREATE INDEX IF NOT EXISTS index_credit_transactions_shopCustomerId ON credit_transactions(shopCustomerId)");db.execSQL("CREATE INDEX IF NOT EXISTS index_credit_transactions_createdAt ON credit_transactions(createdAt)");db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS index_credit_transactions_shopId_mutationId ON credit_transactions(shopId,mutationId)")}}
 val MIGRATION_4_5=object:Migration(4,5){override fun migrate(db:SupportSQLiteDatabase){db.execSQL("ALTER TABLE shop_products ADD COLUMN costPricePaise INTEGER NOT NULL DEFAULT 0")}}
 val MIGRATION_5_6=object:Migration(5,6){override fun migrate(db:SupportSQLiteDatabase){
  db.execSQL("ALTER TABLE sales ADD COLUMN paymentMethod TEXT NOT NULL DEFAULT 'CASH'");db.execSQL("ALTER TABLE sales ADD COLUMN discountPaise INTEGER NOT NULL DEFAULT 0");db.execSQL("ALTER TABLE sales ADD COLUMN subtotalPaise INTEGER NOT NULL DEFAULT 0");db.execSQL("ALTER TABLE sales ADD COLUMN customerName TEXT");db.execSQL("ALTER TABLE sale_items ADD COLUMN costPricePaise INTEGER NOT NULL DEFAULT 0");db.execSQL("ALTER TABLE products ADD COLUMN category TEXT");
  db.execSQL("CREATE INDEX IF NOT EXISTS index_products_barcode ON products(barcode)")}}
 fun create(c:Context)=Room.databaseBuilder(c,LocalDatabase::class.java,"localdukaan.db").addMigrations(MIGRATION_1_2,MIGRATION_2_3,MIGRATION_3_4,MIGRATION_4_5,MIGRATION_5_6).build()}}
